### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/Poplin#11]
Very urgent. Please copy FAQ page (http://ok.gop/faq/) from OKGOP site and add it to a new FAQ page on Poplin. Login creds:

brettafarley/4forjesus

**Comment by supportast** [comment]
Please share the URL urgently as  http://poplin.vsstaging.net/ is not available

**Comment by supportast** [comment]
I have made a section for the FAQ. Please check .

**Comment by brettfarley** [comment]
Please make the background color for each heading (ex. "Control Spending") the same red as on the rest of the site.

**Comment by supportast** [comment]
Done .  FAQ is added in main menu . Please check and let me know if I need to change its position
