### ISSUE TITLE
Setup theme asap

### ISSUE THREAD

**Issue by brettfarley** [VeritasStrategies/Poplin#2]
We need to have this site done before next Monday, so we need to work fast.

Please use the One Host theme from the Martinez site for this Popline site. BUT... I wan the light version of the theme used, NOT the dark version.

I want it to look similar to this theme demo: http://preview.ab-themes.com/andy/

The client prefers the 'Andy' theme but the light version of the One Host theme is very similar, so we don't have to buy a new theme from Themeforest.

**Comment by arish-ricom** [comment]
Dear Brett,

The OneHost theme is not working out. Can we use Dante Theme instead where it is possible to make the layout as seen in the demo link provided by client.

I tried working with OnHost theme and it is not coming out well and is getting messy.

Thanks & Regards
Arish

**Comment by brettfarley** [comment]
If you can make the Dante theme look like the One Host theme, that's fine. We want the layout and elements to be the same as the Martinez site.

Brett

--sent from my iPhone

**Comment by arish-ricom** [comment]
Sure Brett.

**Comment by brettfarley** [comment]
Please stage this site at poplin.vsstaging.net

**Comment by arish-ricom** [comment]
Santosh,

create the site similar to this:

http://www.electryanmartinez.com/

Thanks & Regards
Arish
